### ISSUE TITLE
Syslog crash

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#184]
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at java.lang.String.charAt(String.java:646)
at org.productivity.java.syslog4j.server.impl.event.SyslogServerEvent.parsePriority(Unknown Source)
at org.productivity.java.syslog4j.server.impl.event.SyslogServerEvent.parse(Unknown Source)
at org.productivity.java.syslog4j.server.impl.event.SyslogServerEvent.<init>(Unknown Source)
at org.productivity.java.syslog4j.server.impl.AbstractSyslogServer.createEvent(Unknown Source)
at org.productivity.java.syslog4j.server.impl.net.udp.UDPNetSyslogServer.run(Unknown Source)
at acleague.syslog.LeagueApp$.delayedEndpoint$acleague$syslog$LeagueApp$1(LeagueApp.scala:31)
at acleague.syslog.LeagueApp$delayedInit$body.apply(LeagueApp.scala:8)
at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
at scala.App$$anonfun$main$1.apply(App.scala:76)
at scala.App$$anonfun$main$1.apply(App.scala:76)
at scala.collection.immutable.List.foreach(List.scala:381)
at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
at scala.App$class.main(App.scala:76)
at acleague.syslog.LeagueApp$.main(LeagueApp.scala:8)
at acleague.syslog.LeagueApp.main(LeagueApp.scala)
```

**Comment by ScalaWilliam** [comment]
e602ffadf11b07254dab3032d54ebb61c90d24e2
