### ISSUE TITLE
504 due to broken glitch.me

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#399]
I posted up a Tweet here: https://twitter.com/ScalaWilliam/status/880212927734702081

Here's the error log:
```
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: play.api.UnexpectedException: Unexpected exception[RuntimeException: Received unexpected response 504 for https://actionfps-nicknames.glitch.me/nicknames.tsv]
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:251)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:230)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:229)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: Caused by: java.lang.RuntimeException: Received unexpected response 504 for https://actionfps-nicknames.glitch.me/nicknames.tsv
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at providers.ReferenceProvider$stateMachine$macro$116$1.apply(ReferenceProvider.scala:58)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at providers.ReferenceProvider$stateMachine$macro$116$1.apply(ReferenceProvider.scala:49)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
Jun 28 23:53:13 odin.duel.gg run.sh[24931]: at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
Jun 28 23:53:17 odin.duel.gg run.sh[24931]: %PARSER_ERROR[coloredLevel] a.i.TcpListener - New connection accepted
```

Must create an alternative mode of loading to prevent this issue from happening again, as glitch.me has glitched several times already.

**Comment by ScalaWilliam** [comment]
We moved away from this microservice world, now this is irrelevant
